"""empty message

Revision ID: ef86d86748f7
Revises: 
Create Date: 2024-02-04 11:08:41.257051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef86d86748f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('profession', sa.String(length=40), nullable=True),
    sa.Column('time_for_patient', sa.String(length=4), nullable=True),
    sa.Column('work_time', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=15), nullable=True),
    sa.Column('mail', sa.String(length=50), nullable=True),
    sa.Column('mon_start', sa.String(length=6), nullable=True),
    sa.Column('mon_end', sa.String(length=6), nullable=True),
    sa.Column('tue_start', sa.String(length=6), nullable=True),
    sa.Column('tue_end', sa.String(length=6), nullable=True),
    sa.Column('wed_start', sa.String(length=6), nullable=True),
    sa.Column('wed_end', sa.String(length=6), nullable=True),
    sa.Column('thu_start', sa.String(length=6), nullable=True),
    sa.Column('thu_end', sa.String(length=6), nullable=True),
    sa.Column('fri_start', sa.String(length=6), nullable=True),
    sa.Column('fri_end', sa.String(length=6), nullable=True),
    sa.Column('sat_start', sa.String(length=6), nullable=True),
    sa.Column('sat_end', sa.String(length=6), nullable=True),
    sa.Column('sun_start', sa.String(length=6), nullable=True),
    sa.Column('sun_end', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('surname', sa.String(length=50), nullable=True),
    sa.Column('visit_time_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('visit_time_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('mail', sa.String(length=50), nullable=True),
    sa.Column('id_code', sa.String(length=20), nullable=True),
    sa.Column('send_remind_sms', sa.Boolean(), nullable=True),
    sa.Column('arrived', sa.Boolean(), nullable=True),
    sa.Column('send_by_clinic', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Patients_data_age', sa.Integer(), nullable=True),
    sa.Column('rows_per_page', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('patients')
    op.drop_table('holidays')
    op.drop_table('doctors')
    # ### end Alembic commands ###
